/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.scheme;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.scheme.Comparison#getNum1 <em>Num1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.scheme.Comparison#getNum2 <em>Num2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.scheme.SchemePackage#getComparison()
 * @model
 * @generated
 */
public interface Comparison extends EObject
{
  /**
   * Returns the value of the '<em><b>Num1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num1</em>' attribute.
   * @see #setNum1(String)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getComparison_Num1()
   * @model
   * @generated
   */
  String getNum1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Comparison#getNum1 <em>Num1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num1</em>' attribute.
   * @see #getNum1()
   * @generated
   */
  void setNum1(String value);

  /**
   * Returns the value of the '<em><b>Num2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num2</em>' attribute.
   * @see #setNum2(String)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getComparison_Num2()
   * @model
   * @generated
   */
  String getNum2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Comparison#getNum2 <em>Num2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num2</em>' attribute.
   * @see #getNum2()
   * @generated
   */
  void setNum2(String value);

} // Comparison
