/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.scheme;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.scheme.Expression#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.scheme.Expression#getOper <em>Oper</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.scheme.Expression#getCond <em>Cond</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.scheme.Expression#getSet <em>Set</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.scheme.Expression#getApp <em>App</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.scheme.Expression#getMult <em>Mult</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.scheme.SchemePackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Constant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' attribute.
   * @see #setConstant(String)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getExpression_Constant()
   * @model
   * @generated
   */
  String getConstant();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Expression#getConstant <em>Constant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' attribute.
   * @see #getConstant()
   * @generated
   */
  void setConstant(String value);

  /**
   * Returns the value of the '<em><b>Oper</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oper</em>' containment reference.
   * @see #setOper(Operation)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getExpression_Oper()
   * @model containment="true"
   * @generated
   */
  Operation getOper();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Expression#getOper <em>Oper</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Oper</em>' containment reference.
   * @see #getOper()
   * @generated
   */
  void setOper(Operation value);

  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Conditional)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getExpression_Cond()
   * @model containment="true"
   * @generated
   */
  Conditional getCond();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Expression#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Conditional value);

  /**
   * Returns the value of the '<em><b>Set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set</em>' containment reference.
   * @see #setSet(Set)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getExpression_Set()
   * @model containment="true"
   * @generated
   */
  Set getSet();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Expression#getSet <em>Set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Set</em>' containment reference.
   * @see #getSet()
   * @generated
   */
  void setSet(Set value);

  /**
   * Returns the value of the '<em><b>App</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>App</em>' containment reference.
   * @see #setApp(Application)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getExpression_App()
   * @model containment="true"
   * @generated
   */
  Application getApp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Expression#getApp <em>App</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>App</em>' containment reference.
   * @see #getApp()
   * @generated
   */
  void setApp(Application value);

  /**
   * Returns the value of the '<em><b>Mult</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mult</em>' containment reference.
   * @see #setMult(MultipleCondition)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getExpression_Mult()
   * @model containment="true"
   * @generated
   */
  MultipleCondition getMult();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Expression#getMult <em>Mult</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mult</em>' containment reference.
   * @see #getMult()
   * @generated
   */
  void setMult(MultipleCondition value);

} // Expression
