/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.scheme;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigonometry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.scheme.Trigonometry#getTrig <em>Trig</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.scheme.Trigonometry#getNumb <em>Numb</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.scheme.SchemePackage#getTrigonometry()
 * @model
 * @generated
 */
public interface Trigonometry extends EObject
{
  /**
   * Returns the value of the '<em><b>Trig</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trig</em>' attribute.
   * @see #setTrig(String)
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getTrigonometry_Trig()
   * @model
   * @generated
   */
  String getTrig();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.scheme.Trigonometry#getTrig <em>Trig</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trig</em>' attribute.
   * @see #getTrig()
   * @generated
   */
  void setTrig(String value);

  /**
   * Returns the value of the '<em><b>Numb</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numb</em>' attribute list.
   * @see org.xtext.example.mydsl.scheme.SchemePackage#getTrigonometry_Numb()
   * @model unique="false"
   * @generated
   */
  EList<String> getNumb();

} // Trigonometry
