/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.scheme.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.mydsl.scheme.Calculate;
import org.xtext.example.mydsl.scheme.SchemePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Calculate</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.scheme.impl.CalculateImpl#getCalculate <em>Calculate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.scheme.impl.CalculateImpl#getNumb <em>Numb</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CalculateImpl extends MinimalEObjectImpl.Container implements Calculate
{
  /**
   * The default value of the '{@link #getCalculate() <em>Calculate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCalculate()
   * @generated
   * @ordered
   */
  protected static final String CALCULATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCalculate() <em>Calculate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCalculate()
   * @generated
   * @ordered
   */
  protected String calculate = CALCULATE_EDEFAULT;

  /**
   * The cached value of the '{@link #getNumb() <em>Numb</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumb()
   * @generated
   * @ordered
   */
  protected EList<String> numb;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CalculateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SchemePackage.Literals.CALCULATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCalculate()
  {
    return calculate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCalculate(String newCalculate)
  {
    String oldCalculate = calculate;
    calculate = newCalculate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SchemePackage.CALCULATE__CALCULATE, oldCalculate, calculate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getNumb()
  {
    if (numb == null)
    {
      numb = new EDataTypeEList<String>(String.class, this, SchemePackage.CALCULATE__NUMB);
    }
    return numb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SchemePackage.CALCULATE__CALCULATE:
        return getCalculate();
      case SchemePackage.CALCULATE__NUMB:
        return getNumb();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SchemePackage.CALCULATE__CALCULATE:
        setCalculate((String)newValue);
        return;
      case SchemePackage.CALCULATE__NUMB:
        getNumb().clear();
        getNumb().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SchemePackage.CALCULATE__CALCULATE:
        setCalculate(CALCULATE_EDEFAULT);
        return;
      case SchemePackage.CALCULATE__NUMB:
        getNumb().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SchemePackage.CALCULATE__CALCULATE:
        return CALCULATE_EDEFAULT == null ? calculate != null : !CALCULATE_EDEFAULT.equals(calculate);
      case SchemePackage.CALCULATE__NUMB:
        return numb != null && !numb.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (calculate: ");
    result.append(calculate);
    result.append(", numb: ");
    result.append(numb);
    result.append(')');
    return result.toString();
  }

} //CalculateImpl
